// react-implementation/src/components/SearchBar.tsx
import React, { useState } from 'react';
import { Search } from 'lucide-react';

interface SearchBarProps {
  onSearch: (query: string) => void;
  isLoading?: boolean;
}

const SearchBar: React.FC<SearchBarProps> = ({ onSearch, isLoading = false }) => {
  const [query, setQuery] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSearch(query);
  };

  return (
    <div className="w-full max-w-2xl mx-auto mb-8">
      <form onSubmit={handleSubmit} className="relative">
        <div className="relative">
          <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 h-5 w-5 text-slate-400" />
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search for apartments..."
            className="w-full pl-12 pr-4 py-4 bg-slate-800 border border-slate-700 rounded-xl text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-lg"
          />
        </div>
        <button
          type="submit"
          disabled={isLoading}
          className="absolute right-2 top-1/2 transform -translate-y-1/2 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-semibold py-2 px-6 rounded-lg transition-all duration-200"
        >
          {isLoading ? 'Searching...' : 'Search'}
        </button>
      </form>
    </div>
  );
};

export default SearchBar;

// src/components/SearchBar.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { Search } from 'lucide-vue-next'

interface SearchBarProps {
  isLoading?: boolean
}

withDefaults(defineProps<SearchBarProps>(), {
  isLoading: false,
})

const emit = defineEmits<{
  search: [query: string]
}>()

const query = ref('')

const examples = [
  'Try: Apartment in Vienna with a walk in shower for < 1500€ per month',
  'Try: Apartment in Augsburg with a dining table for at least 4 people for < 1700€ per month',
  'Try: Apartment in Vienna with a high bed for < 1200€ per month',
]

const exampleHint = ref('')

exampleHint.value = examples[Math.floor(Math.random() * examples.length)]

const handleSubmit = (e: Event) => {
  e.preventDefault()
  emit('search', query.value)
  exampleHint.value = ''
}
</script>

<template>
  <div class="w-full max-w-2xl mx-auto mb-8">
    <form @submit="handleSubmit" class="relative">
      <div class="relative">
        <Search class="absolute left-4 top-1/2 transform -translate-y-1/2 h-5 w-5 text-slate-400" />
        <input
          v-model="query"
          type="text"
          placeholder="What are you looking for?"
          style="padding-right: 152px"
          class="w-full pl-12 py-4 bg-slate-800 border border-slate-700 rounded-xl text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-lg"
        />
      </div>
      <button
        type="submit"
        :disabled="isLoading"
        class="absolute right-2 top-1/2 transform -translate-y-1/2 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-semibold py-2 px-6 rounded-lg transition-all duration-200"
      >
        {{ isLoading ? 'Searching...' : 'Search' }}
      </button>
    </form>
    <p class="mt-2 pl-12 text-slate-400 text-sm">{{ exampleHint }}</p>
  </div>
</template>
